apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pp
  labels:
    app: tcli-dlv
  name: tcli-dlv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcli-dlv
  template:
    metadata:
      labels:
        app: tcli-dlv
      annotations:
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      containers:
        - name: dlv
          imagePullPolicy: IfNotPresent
          image: 'eggitayi/k8sgodlv:v1.0'
          args: ['./main.go']
          ports:
            - name: tcp-2345
              protocol: TCP
              containerPort: 2345
          volumeMounts:
            - name: tcli
              readOnly: false
              mountPath: /app
      serviceAccount: default
      initContainers: []
      volumes:
        - hostPath:
            path: /root/dlv/tcli
          name: tcli
      imagePullSecrets: null
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  namespace: pp
  labels:
    app: dlv
  name: dlv
spec:
  sessionAffinity: None
  selector:
    app: tcli-dlv
  ports:
    - name: dlv
      protocol: TCP
      targetPort: 2345
      port: 2345
      nodePort: 9900
  type: NodePort
